---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
    privileged: true
    command: /sbin/init
  - name: centos6
    image: centos:6
    privileged: true
    command: /sbin/init
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  # name: testinfra
  # lint:
  #   name: flake8
  name: ansible
  lint:
    name: ansible-lint
